import type { NextPage } from "next";
import Head from "next/head";
import { useSession, signIn, signOut } from "next-auth/react";
import { trpc } from "../utils/trpc";
import Landing from "../components/Landing";
import ItemContainer from "../components/ItemContainer";
import Upcoming from "../components/Upcoming";

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const Home: NextPage = () => {
  const { data, status } = useSession();

  if (status === "loading") {
    return (
      <div>
        <p>Loading...</p>
      </div>
    );
  }

  if (!data) {
    return <Landing />;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <p>
          Signed in as{" "}
          <span className="font-bold text-purple-500">{data.user?.name}</span> -
          <span className="font-bold text-purple-500">{data.user?.id}</span>
        </p>
        <button className="text-white" onClick={() => signOut()}>
          Sign out
        </button>
        {/* // * Menu */}
        {/* // * Main Canvas */}
        <div className="container flex flex-col max-w-7xl h-screen border border-gray-700 items-center gap-10">
          {/* // ? Dashed Line */}
          <div className="absolute h-screen w-[2px] bg-transparent border-2 border-dashed border-gray-500 -z-10"></div>
          <ItemContainer />
        </div>
      </div>
    </>
  );
};

export default Home;
